<?php
/**
 * اطلاعات اولیه موجودی‌کالا
 *
 * در نسخه واقعی این آرایه به جداول کالا، فروشنده و موجودی در دیتابیس وصل می‌شود.
 * ساختار داده طوری نگه داشته شده که اتصال به MySQL یا API در مرحله بعد ساده باشد.
 */

$filterOptions = [
    'cities' => ['همه شهرها', 'تهران', 'کرج', 'مشهد', 'اصفهان', 'شیراز'],
    'categories' => ['همه دسته‌ها', 'قطعات موتور', 'سیستم سوخت‌رسانی', 'قطعات بدنه', 'برق خودرو', 'لوازم مصرفی'],
    'brands' => ['همه برندها', 'MVM', 'ایران خودرو', 'سایپا', 'پژو', 'رنو', 'بوش'],
    'conditions' => ['همه وضعیت‌ها', 'نو', 'دست دوم'],
    'test_days' => ['همه مهلت تست', 'ندارد', 'یک روز', 'دو روز', 'یک هفته'],
    'warranty' => ['همه گارانتی', 'دارد', 'ندارد'],
    'payments' => ['همه نوع پرداخت', 'نقدی', 'نقد و اقساط', 'آنلاین'],
];

$products = [
    [
        'id' => 'mvm110-cylinder-head',
        'title' => 'سرسیلندر MVM 110',
        'code' => '100071',
        'category' => 'قطعات موتور',
        'brand' => 'MVM',
        'vehicle' => 'MVM 110',
        'image' => 'assets/images/cylinder-head.svg',
        'description' => 'سرسیلندر آماده نصب برای MVM 110، بررسی‌شده و مناسب مدل‌های چهار سیلندر.',
        'tags' => ['سرسیلندر', 'MVM110', 'موتور'],
        'offers' => [
            [
                'seller' => 'یدک‌پارت مرکزی',
                'phone' => '09120000001',
                'city' => 'تهران',
                'price' => 1350000,
                'condition' => 'نو',
                'warranty' => 'دارد',
                'test' => 'دو روز',
                'payment' => 'نقدی',
                'date' => '1405/06/02',
                'verified' => true,
            ],
            [
                'seller' => 'قطعه‌یار البرز',
                'phone' => '09120000002',
                'city' => 'کرج',
                'price' => 1120000,
                'condition' => 'دست دوم',
                'warranty' => 'ندارد',
                'test' => 'یک روز',
                'payment' => 'نقدی',
                'date' => '1405/06/02',
                'verified' => true,
            ],
            [
                'seller' => 'موتورپارت توس',
                'phone' => '09120000003',
                'city' => 'مشهد',
                'price' => 1480000,
                'condition' => 'نو',
                'warranty' => 'دارد',
                'test' => 'یک هفته',
                'payment' => 'آنلاین',
                'date' => '1405/06/01',
                'verified' => false,
            ],
        ],
    ],
    [
        'id' => 'peugeot405-fuel-pump',
        'title' => 'پمپ بنزین پژو ۴۰۵',
        'code' => '100118',
        'category' => 'سیستم سوخت‌رسانی',
        'brand' => 'پژو',
        'vehicle' => 'پژو ۴۰۵ / پارس',
        'image' => 'assets/images/fuel-pump.svg',
        'description' => 'پمپ بنزین کامل پژو ۴۰۵ و پارس با سوکت فابریک و امکان تست قبل از ارسال.',
        'tags' => ['پمپ بنزین', 'پژو 405', 'پارس'],
        'offers' => [
            [
                'seller' => 'اتولاین جنوب',
                'phone' => '09120000004',
                'city' => 'تهران',
                'price' => 890000,
                'condition' => 'نو',
                'warranty' => 'دارد',
                'test' => 'دو روز',
                'payment' => 'نقدی',
                'date' => '1405/06/02',
                'verified' => true,
            ],
            [
                'seller' => 'پارس‌یدک',
                'phone' => '09120000005',
                'city' => 'اصفهان',
                'price' => 745000,
                'condition' => 'دست دوم',
                'warranty' => 'ندارد',
                'test' => 'یک روز',
                'payment' => 'نقد و اقساط',
                'date' => '1405/06/02',
                'verified' => true,
            ],
        ],
    ],
    [
        'id' => 'pride-clutch-kit',
        'title' => 'دیسک و صفحه پراید',
        'code' => '100204',
        'category' => 'قطعات موتور',
        'brand' => 'سایپا',
        'vehicle' => 'پراید ۱۳۱ / صبا',
        'image' => 'assets/images/clutch.svg',
        'description' => 'کیت کامل دیسک و صفحه پراید با بسته‌بندی سالم و مناسب مصرف روزانه.',
        'tags' => ['دیسک و صفحه', 'پراید', 'کلاچ'],
        'offers' => [
            [
                'seller' => 'فروشگاه خودروکار',
                'phone' => '09120000006',
                'city' => 'اصفهان',
                'price' => 1680000,
                'condition' => 'نو',
                'warranty' => 'دارد',
                'test' => 'یک هفته',
                'payment' => 'نقد و اقساط',
                'date' => '1405/06/02',
                'verified' => true,
            ],
            [
                'seller' => 'یدک‌سرای شرق',
                'phone' => '09120000007',
                'city' => 'مشهد',
                'price' => 1550000,
                'condition' => 'نو',
                'warranty' => 'دارد',
                'test' => 'دو روز',
                'payment' => 'نقدی',
                'date' => '1405/06/01',
                'verified' => false,
            ],
        ],
    ],
    [
        'id' => 'dena-plus-headlight',
        'title' => 'چراغ جلو دنا پلاس',
        'code' => '100325',
        'category' => 'قطعات بدنه',
        'brand' => 'ایران خودرو',
        'vehicle' => 'دنا پلاس',
        'image' => 'assets/images/headlight.svg',
        'description' => 'چراغ جلو دنا پلاس، شفاف و سالم، مناسب سمت راننده و قابل ارسال به سراسر کشور.',
        'tags' => ['چراغ جلو', 'دنا پلاس', 'بدنه'],
        'offers' => [
            [
                'seller' => 'بدنه‌کار تهران',
                'phone' => '09120000008',
                'city' => 'تهران',
                'price' => 2950000,
                'condition' => 'نو',
                'warranty' => 'دارد',
                'test' => 'دو روز',
                'payment' => 'آنلاین',
                'date' => '1405/06/02',
                'verified' => true,
            ],
            [
                'seller' => 'اتاق‌سازی شیراز',
                'phone' => '09120000009',
                'city' => 'شیراز',
                'price' => 2100000,
                'condition' => 'دست دوم',
                'warranty' => 'ندارد',
                'test' => 'ندارد',
                'payment' => 'نقدی',
                'date' => '1405/05/31',
                'verified' => true,
            ],
        ],
    ],
    [
        'id' => 'tiba-ac-compressor',
        'title' => 'کمپرسور کولر تیبا',
        'code' => '100417',
        'category' => 'برق خودرو',
        'brand' => 'سایپا',
        'vehicle' => 'تیبا / ساینا',
        'image' => 'assets/images/compressor.svg',
        'description' => 'کمپرسور کولر تیبا و ساینا، تست‌شده با ضمانت سلامت هنگام تحویل.',
        'tags' => ['کمپرسور کولر', 'تیبا', 'ساینا'],
        'offers' => [
            [
                'seller' => 'کولر خودرو نوین',
                'phone' => '09120000010',
                'city' => 'کرج',
                'price' => 4200000,
                'condition' => 'دست دوم',
                'warranty' => 'دارد',
                'test' => 'یک هفته',
                'payment' => 'نقد و اقساط',
                'date' => '1405/06/02',
                'verified' => true,
            ],
            [
                'seller' => 'برق‌کاران خودرو',
                'phone' => '09120000011',
                'city' => 'تهران',
                'price' => 4950000,
                'condition' => 'نو',
                'warranty' => 'دارد',
                'test' => 'دو روز',
                'payment' => 'آنلاین',
                'date' => '1405/06/01',
                'verified' => false,
            ],
        ],
    ],
    [
        'id' => 'renault-l90-timing-belt',
        'title' => 'کیت تسمه تایم رنو L90',
        'code' => '100522',
        'category' => 'لوازم مصرفی',
        'brand' => 'رنو',
        'vehicle' => 'رنو L90 / ساندرو',
        'image' => 'assets/images/timing-belt.svg',
        'description' => 'کیت تسمه تایم کامل رنو L90 با رولبرینگ و ضمانت اصالت کالا.',
        'tags' => ['تسمه تایم', 'L90', 'ساندرو'],
        'offers' => [
            [
                'seller' => 'رنوپارت',
                'phone' => '09120000012',
                'city' => 'تهران',
                'price' => 2350000,
                'condition' => 'نو',
                'warranty' => 'دارد',
                'test' => 'یک هفته',
                'payment' => 'نقدی',
                'date' => '1405/06/02',
                'verified' => true,
            ],
            [
                'seller' => 'فرانس‌یدک',
                'phone' => '09120000013',
                'city' => 'مشهد',
                'price' => 2190000,
                'condition' => 'نو',
                'warranty' => 'دارد',
                'test' => 'دو روز',
                'payment' => 'نقدی',
                'date' => '1405/05/30',
                'verified' => true,
            ],
        ],
    ],
    [
        'id' => 'samand-brake-pads',
        'title' => 'لنت ترمز جلو سمند',
        'code' => '100611',
        'category' => 'لوازم مصرفی',
        'brand' => 'ایران خودرو',
        'vehicle' => 'سمند / دنا',
        'image' => 'assets/images/brake-pad.svg',
        'description' => 'لنت ترمز جلو سمند و دنا، کم‌صدا و مناسب استفاده شهری.',
        'tags' => ['لنت ترمز', 'سمند', 'دنا'],
        'offers' => [
            [
                'seller' => 'ترمز ایمن',
                'phone' => '09120000014',
                'city' => 'اصفهان',
                'price' => 680000,
                'condition' => 'نو',
                'warranty' => 'دارد',
                'test' => 'دو روز',
                'payment' => 'نقدی',
                'date' => '1405/06/02',
                'verified' => true,
            ],
            [
                'seller' => 'یدک‌مارکت فارس',
                'phone' => '09120000015',
                'city' => 'شیراز',
                'price' => 620000,
                'condition' => 'نو',
                'warranty' => 'ندارد',
                'test' => 'ندارد',
                'payment' => 'آنلاین',
                'date' => '1405/06/01',
                'verified' => false,
            ],
        ],
    ],
    [
        'id' => 'bosch-66ah-battery',
        'title' => 'باتری ۶۶ آمپر بوش',
        'code' => '100734',
        'category' => 'برق خودرو',
        'brand' => 'بوش',
        'vehicle' => 'مناسب خودروهای سواری',
        'image' => 'assets/images/battery.svg',
        'description' => 'باتری ۶۶ آمپر بوش با تاریخ تولید جدید و ارسال سریع در شهرهای منتخب.',
        'tags' => ['باتری', 'بوش', '66 آمپر'],
        'offers' => [
            [
                'seller' => 'باتری‌سنتر',
                'phone' => '09120000016',
                'city' => 'تهران',
                'price' => 3180000,
                'condition' => 'نو',
                'warranty' => 'دارد',
                'test' => 'یک هفته',
                'payment' => 'نقد و اقساط',
                'date' => '1405/06/02',
                'verified' => true,
            ],
            [
                'seller' => 'شارژ خودرو',
                'phone' => '09120000017',
                'city' => 'کرج',
                'price' => 3050000,
                'condition' => 'نو',
                'warranty' => 'دارد',
                'test' => 'یک هفته',
                'payment' => 'آنلاین',
                'date' => '1405/06/02',
                'verified' => true,
            ],
        ],
    ],
];
